/**
 * Backfill script: applies category mappings to transactions based on normalized_merchant.
 * 
 * Reads: transactions-with-category-paths.json (generated by transform-categories.ts)
 * 
 * For each mapping entry:
 *   1. Find all transactions with matching normalizedMerchant
 *   2. Look up category IDs from categoryPaths
 *   3. Apply categories (with ancestry expansion) and ignore flag
 * 
 * Run with: npx tsx src/scripts/backfill-categories-from-mapping.ts
 */

import "dotenv/config";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import { prisma } from "../lib/prisma.js";
import { expandCategoryIds, setTransactionCategories } from "../services/rules.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface MappingEntry {
  normalized_merchant: string;
  categoryPaths: string[][];
  ignore: boolean;
}

interface CategoryWithParent {
  id: string;
  name: string;
  parentId: string | null;
}

/**
 * Extract all unique category paths from mappings and create them in DB.
 * Returns a refreshed category lookup.
 */
async function ensureCategoriesExist(
  mappings: MappingEntry[]
): Promise<{ created: number; existing: number }> {
  // Collect all unique paths
  const allPaths = new Set<string>();
  for (const m of mappings) {
    for (const path of m.categoryPaths) {
      // Add the full path and all parent paths
      // e.g., ["Groceries", "Supermarket"] adds both ["Groceries"] and ["Groceries", "Supermarket"]
      for (let i = 1; i <= path.length; i++) {
        allPaths.add(JSON.stringify(path.slice(0, i)));
      }
    }
  }

  // Sort by length so parents are created before children
  const sortedPaths = Array.from(allPaths)
    .map((p) => JSON.parse(p) as string[])
    .sort((a, b) => a.length - b.length);

  let created = 0;
  let existing = 0;

  for (const path of sortedPaths) {
    if (path.length === 1) {
      // Root category
      const name = path[0];
      const exists = await prisma.category.findUnique({ where: { name } });
      if (exists) {
        existing++;
      } else {
        await prisma.category.create({ data: { name } });
        created++;
        console.log(`  Created root category: ${name}`);
      }
    } else if (path.length === 2) {
      // Child category
      const [parentName, childName] = path;
      const parent = await prisma.category.findUnique({ where: { name: parentName } });
      if (!parent) {
        console.warn(`  Parent not found for ${childName}: ${parentName}`);
        continue;
      }

      const exists = await prisma.category.findUnique({ where: { name: childName } });
      if (exists) {
        // Check if it has the right parent
        if (exists.parentId !== parent.id) {
          console.warn(`  Category ${childName} exists but has different parent`);
        }
        existing++;
      } else {
        await prisma.category.create({
          data: { name: childName, parentId: parent.id },
        });
        created++;
        console.log(`  Created category: ${parentName} > ${childName}`);
      }
    }
  }

  return { created, existing };
}

async function buildCategoryLookup(): Promise<{
  byName: Map<string, CategoryWithParent[]>;
  byId: Map<string, CategoryWithParent>;
}> {
  const categories = await prisma.category.findMany({
    select: { id: true, name: true, parentId: true },
  });

  // Group by name (there could be multiple categories with same name, different parents)
  const byName = new Map<string, CategoryWithParent[]>();
  const byId = new Map<string, CategoryWithParent>();

  for (const cat of categories) {
    byId.set(cat.id, cat);
    const existing = byName.get(cat.name) || [];
    existing.push(cat);
    byName.set(cat.name, existing);
  }

  return { byName, byId };
}

function resolveCategoryPath(
  path: string[],
  byName: Map<string, CategoryWithParent[]>,
  byId: Map<string, CategoryWithParent>
): string | null {
  if (path.length === 0) return null;

  if (path.length === 1) {
    // Root category - find one with no parent
    const candidates = byName.get(path[0]) || [];
    const root = candidates.find((c) => c.parentId === null);
    return root?.id || null;
  }

  if (path.length === 2) {
    const [parentName, childName] = path;

    // Find parent (should be root)
    const parentCandidates = byName.get(parentName) || [];
    const parent = parentCandidates.find((c) => c.parentId === null);
    if (!parent) return null;

    // Find child with this parent
    const childCandidates = byName.get(childName) || [];
    const child = childCandidates.find((c) => c.parentId === parent.id);
    return child?.id || null;
  }

  // Longer paths not supported yet
  console.warn(`Path length ${path.length} not supported: ${JSON.stringify(path)}`);
  return null;
}

async function main() {
  const projectRoot = path.resolve(__dirname, "../../..");
  const inputPath = path.join(projectRoot, "transactions-with-category-paths.json");

  console.log(`Reading mappings from: ${inputPath}`);
  const raw = fs.readFileSync(inputPath, "utf-8");
  const mappings: MappingEntry[] = JSON.parse(raw);

  console.log(`Loaded ${mappings.length} merchant mappings`);

  // Create missing categories first
  console.log("\nEnsuring categories exist...");
  const { created, existing } = await ensureCategoriesExist(mappings);
  console.log(`  Created: ${created}, Already existed: ${existing}`);

  // Build category lookup
  const { byName, byId } = await buildCategoryLookup();
  console.log(`Loaded ${byId.size} categories from database`);

  // Stats
  let transactionsUpdated = 0;
  let transactionsSkipped = 0;
  let mappingsWithNoMatch = 0;
  let mappingsWithCategoryError: string[] = [];

  for (const mapping of mappings) {
    // Find transactions with this normalized_merchant
    const transactions = await prisma.transaction.findMany({
      where: {
        normalizedMerchant: mapping.normalized_merchant,
        categoriesLockedByUser: false, // Don't overwrite manual assignments
      },
      select: { id: true, ignoreSource: true },
    });

    if (transactions.length === 0) {
      mappingsWithNoMatch++;
      continue;
    }

    // Resolve category paths to IDs
    const categoryIds: string[] = [];
    let hasError = false;

    for (const catPath of mapping.categoryPaths) {
      const catId = resolveCategoryPath(catPath, byName, byId);
      if (!catId) {
        mappingsWithCategoryError.push(
          `${mapping.normalized_merchant}: ${JSON.stringify(catPath)}`
        );
        hasError = true;
        break;
      }
      categoryIds.push(catId);
    }

    if (hasError) continue;

    // Expand categories to include ancestors
    const expanded = await expandCategoryIds(categoryIds, "rule", null);

    // Apply to each transaction
    for (const tx of transactions) {
      await setTransactionCategories(tx.id, expanded);

      // Apply ignore flag if not manually set
      if (tx.ignoreSource !== "manual") {
        await prisma.transaction.update({
          where: { id: tx.id },
          data: {
            isIgnored: mapping.ignore,
            ignoreSource: mapping.ignore ? "rule" : null,
          },
        });
      }

      transactionsUpdated++;
    }
  }

  // Summary
  console.log("\n" + "─".repeat(60));
  console.log("Backfill complete");
  console.log("─".repeat(60));
  console.log(`  Transactions updated:     ${transactionsUpdated}`);
  console.log(`  Transactions skipped:     ${transactionsSkipped}`);
  console.log(`  Mappings with no matches: ${mappingsWithNoMatch}`);
  console.log(`  Category lookup errors:   ${mappingsWithCategoryError.length}`);

  if (mappingsWithCategoryError.length > 0) {
    console.log("\nCategory paths that could not be resolved:");
    for (const err of mappingsWithCategoryError.slice(0, 20)) {
      console.log(`  - ${err}`);
    }
    if (mappingsWithCategoryError.length > 20) {
      console.log(`  ... and ${mappingsWithCategoryError.length - 20} more`);
    }
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
